account/urls.py
from django.urls import path,include
from .views import *

app_name="account"

urlpatterns = [
    path("register",register_page,name="register"),
    path("login",login_page,name="login"),
    path('logout', logout_page, name='logout'),
    # path('delete/', delete_account, name='delete_account'),

    
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from home.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",home_page,name="home"),
    path("contact",contact_page,name="contact"),
    path("about",about_page,name="about"),
    path("account/",include("account.urls")),
    path("exam/",include("exam.urls")),
    path("video/",video_lessons_page,name="video"),
]

exam/urls.py
from django.urls import path,include
from .views import *

app_name="exam"

urlpatterns = [
    path('math_exam/', math_quiz_view, name='math_exam'),
    path('result/<int:correct>/<int:incorrect>/', result, name='result'),
    path('exams/',exams_view,name="exams"),

   
]

account/models.py
from django.db import models

# Create your models here.

exam/models.py
from django.db import models


class Video(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    youtube_url = models.URLField()

    def __str__(self):
        return self.title

home/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms

class RegisterForm(forms.Form):
    username=forms.CharField(max_length=30,label="Username")
    password=forms.CharField(max_length=8,label="Password",widget=forms.PasswordInput)
    confirm=forms.CharField(max_length=8,label="P confirm",widget=forms.PasswordInput)

    def clean(self):
        username=self.cleaned_data["username"]
        password=self.cleaned_data["password"]
        confirm=self.cleaned_data["confirm"]

        if password and confirm and password!=confirm:
            raise forms.ValidationError("Şifreler eyni deyil!")
        values={
            "username":username,
            "password":password
        }
        return values

class LoginForm(forms.Form):
    username=forms.CharField(max_length=30,label="Username")
    password=forms.CharField(max_length=8,label="Password",widget=forms.PasswordInput)

account/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm,LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages



def register_page(request):
    form=RegisterForm(request.POST or None)

    if form.is_valid():
        username=form.cleaned_data.get("username")
        # lastname=form.cleaned_data.get("lastname")
        password=form.cleaned_data.get("password")

        newUser=User(username=username)
        # newUser=User(lastname=lastname)
        newUser.set_password(password)

        newUser.save()

        login(request,newUser)
        messages.success(request, "Uğurla qeydiyyatdan keçdiniz...")  
        return redirect("home")
    
    context={
        "form":form,
    }

    return render (request,"register.html",context)





def login_page(request):
    form=LoginForm(request.POST or None)
    context={
            "form":form,
        }
    
    if form.is_valid():
        username=form.cleaned_data.get("username")
        password=form.cleaned_data.get("password")

        user=authenticate(username=username,password=password)

        if user is None:
            return render(request,"login.html")
        
        login(request,user)
        messages.success(request, "Uğurla giriş ettiniz...")
        return redirect("home")

    return render (request,"login.html",context)



def logout_page(request):
    logout(request)
    return redirect("home")

exam/views.py
# from django.shortcuts import render, redirect
# from django.shortcuts import render, redirect
from django.urls import reverse
from django.shortcuts import render, redirect

def math_quiz_view(request):
    correct_answers = ['B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B']
    score = {'correct': 0, 'incorrect': 0}

    if request.method == 'POST':
        user_answers = [
            request.POST.get('question1'),
            request.POST.get('question2'),
            request.POST.get('question3'),
            request.POST.get('question4'),
            request.POST.get('question5'),
            request.POST.get('question6'),
            request.POST.get('question7'),
            request.POST.get('question8'),
            request.POST.get('question9'),
            request.POST.get('question10'),
        ]
        
        for i, answer in enumerate(user_answers):
            if answer == correct_answers[i]:
                score['correct'] += 1
            else:
                score['incorrect'] += 1

        # URL parametrelerini kullanarak yönlendirme
        return redirect(f"/exam/result/{score['correct']}/{score['incorrect']}")

    return render(request, 'math_quiz.html')

def exams_view(request):
    return render(request,"exams.html")


def result(request, correct, incorrect):
    return render(request, 'math_resault.html', {'correct': correct, 'incorrect': incorrect})

home/views.py
from django.shortcuts import render
from exam.models import Video

# Create your views here.

def home_page(request):
    return render(request,"home.html")

def contact_page(request):
    return render(request,"contact.html")

def about_page(request):
    return render(request,"about.html")

def video_lessons_page(request):
    videos = Video.objects.all() 
    return render(request, "video_lessons.html", {"videos": videos})

templates/about.html
{% extends "base.html" %}

{% load static %}

{% block body %}
    <link rel="stylesheet" href="{% static 'css/about.css' %}">
    <link rel="stylesheet" href="{% static 'css/about-repo.css' %}">
    <div class="container">
        <div class="section1">
            <div class="text_div">
                <h2>Hi there, I’m Steven</h2>
                <p>I'm a paragraph. Click here to add your own text and edit me. I’m a great place for you to tell a story and let your users know a little more about you.</p>

            </div>
    
            <div class="image_div">
                <img src="{% static './images/coursefoto.webp' %}" alt="">
            </div>
        </div>

        <div class="section2">
            <div class="bio_div">
                <h2>Bio</h2>
            </div>

            <div class="bio_text">
                <p>
                    I'm a paragraph. Click here to add your own text and edit me. It’s easy. Just click “Edit Text” or double click me to add your own content and make changes to the font. Feel free to drag and drop me anywhere you like on your page. I’m a great place for you to tell a story and let your users know a little more about you.</p>
                <br>
                <p>This is a great space to write a long text about your company and your services. You can use this space to go into a little more detail about your company. Talk about your team and what services you provide. Tell your visitors the story of how you came up with the idea for your business and what makes you different from your competitors. Make your company stand out and show your visitors who you are.</p>
            </div>


        </div>


        <div class="section3">

            <div class="education_div">
                <h2>Education</h2>
            </div>

            <div class="education_texts">
                <div class="text_divv">
                    <hr>
                    <h2>Bachelor's Degree in Education</h2>
                    <p>I'm a paragraph. Click here to add your own text and edit me. I’m a great place for you to tell a story and let your users know a little more about you.</p>
                    
                </div>
               
               
                <div class="text_div2">
                    <hr>
                    <h2>Master's Degree in Social Studies</h2>
                    <p>I'm a paragraph. Click here to add your own text and edit me. I’m a great place for you to tell a story and let your users know a little more about you.</p>

                </div>
            </div>
        </div>
    </div>


{% endblock body %}
    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/base-repo.css' %}">
    <link rel="stylesheet" href="{% static 'css/hidden-part.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <header>
        <nav class="navbar">
          <div class="logo">
            <div class="logo-img">
              <img src="{% static 'images\logo.svg' %}" alt="logo" />
            </div>
            <h1 class="logo-text">Online Lessons</h1>
          </div>
          <ul class="nav-links" id="nav-links">
            <li><a href="{% url 'home' %}">Ana səhifə</a></li>
            <li><a href="{% url 'video' %}">Video dərslər</a></li>
            <li><a href="{% url 'exam:exams' %}">İmtahanlar</a></li>
            <li><a href="{% url 'about' %}">Haqqımızda</a></li>
            <li><a href="{% url 'contact' %}">Əlaqə</a></li>
            <!-- <li></li> -->
            {% if request.user.is_authenticated %}
        
                <div class="logout_div">
                  <a href="{% url 'account:logout' %}"><i class="fa-solid fa-right-from-bracket"></i></a>
                </div>
                {% else %}
                    <li class="nav-li-login">
                
                      <i class="fa-solid fa-circle-user"></i>
                
                      <a href="{% url 'account:register' %}" class="login">Qeydiyyat</a>
                    </li> 
                {% endif %}
       
          </ul>

          <div class="hidden-part">
            <!-- <div class="hidden-part-flex"> -->
                <div class="dropdown-hidden">
                      
                      <button class="dropbtn-hidden" id="menu-toggle">
                        <i class="fa-solid fa-bars" id="menu-icon"></i>
                    </button>

                    <div class="dropdown-content-hidden">
                      <a href="{% url 'home' %}">Ana səhifə</a>
                      <a href="{% url 'video' %}">Video dərslər</a>
                      <a href="{% url 'exam:exams' %}">İmtahanlar</a>
                      <a href="{% url 'about' %}">Haqqımızda</a>
                      <a href="{% url 'contact' %}">Əlaqə</a>
                      {% if user.is_authenticated %}
                          <a href="{% url 'account:logout' %}">Çıxış edin<i class="fa-solid fa-right-from-bracket"></i></a>
                        {% else %}
                          <a href="{% url 'account:login' %}">Qeydiyyat<i class="fa-solid fa-right-to-bracket"></i></a>
                      {% endif %}
                    </div>
                </div>
            <!-- </div> -->
        </div>  
        

          <!-- <div class="menu-icon" onclick="toggleMenu()">
            <div class="bar1"></div>
            <div class="bar2"></div>
            <div class="bar3"></div>
          </div> -->
        </nav>
      </header>
    </div>

    {% block body %}
    
    {% comment %} ##################### {% endcomment %}
    {% endblock body %}


    <!-- <div class="container"> -->
        <footer class="footer">
        <div class="footer-logo">
          <div class="logo">
            <div class="logo-img">
              <img src="{% static 'images/logo.svg' %}" alt="logo" />
            </div>
            <h1 class="logo-text">Online Lessons</h1>
          </div>
        </div>
        <div class="footer-contact">
          <p>info@mysite.com</p>
          <p>123-456-7890</p>
        </div>
        <div class="footer-links">
          <ul>
            <li><a href="#about">About</a></li>
            <li><a href="#our-services">Our Services</a></li>
            <li><a href="#Assignments">Assignments</a></li>
            <li><a href="#Packages">Packages</a></li>
            <li><a href="#learning-tools">Learning Tools</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div>  
        <div class="footer-copy">
          <p>© 2024 by Online Lessons.</p>
          <p>Powered and secured by Online Lessons</p>
        </div>
      </footer>
    <!-- </div> -->
    </div>
    

    <script src="{% static 'js/hidden-part.js' %}"></script>

    
</body>
</html>

templates/contact.html
{% extends "base.html" %}
{% load static %}

{% block body %}

    <link rel="stylesheet" href="{% static 'css/contact.css' %}">


    

      <!-- ########################################################### -->
    <div class="container">
           <div class="section">
            <div class="contact_div">
                <div class="main_div">
                    <h3>Bizimlə əlaqə</h3>

                    <div class="form_div">
                        <form action="#" method="post">
                            <div class="form-name">

                                <input placeholder="Adınız..." type="text" id="name" name="name" >
                            </div>
                        
                            <div class="form-group">
                                
                                <textarea placeholder="Mesajınız..." id="message" name="message" rows="5"></textarea>
                            </div>
                            <button type="submit" class="comment-btn">Göndər</button>
                        </form>
                    </div>
                </div>
                
            </div>


       </div>
  </div>
    </div>
{% endblock body %}

    

templates/exams.html
{% extends "base.html" %}

{% load static %}

{% block body %}

    <link rel="stylesheet" href="{% static 'css/exams.css' %}">
    <link rel="stylesheet" href="{% static 'css/exams-repo.css' %}">

    <div class="container">
        <div class="exams_type">
            <div class="exams">
                <div class="img_div">   
                    <img src="{% static 'images/math.svg' %}" alt="">
                    <div class="select-class">
                        <button><a href="">5-8</a></button>
                        <button><a href="">9-11</a></button>
                    </div>
                </div> 
                <p>Riyaziyyat</p>
                <!-- <a href="{% url 'exam:math_exam' %}"><button class="start">Başlayın</button></a> -->
                <button class="start">Başlayın</button>
            </div>


            <div class="exams">
                <div class="img_div">
                    <img src="{% static 'images/open-book.png' %}" alt="">
                    <div class="select-class">
                        <button><a href="">5-8</a></button>
                        <button><a href="">9-11</a></button>
                    </div>
                </div>
                <p>Azərbaycan dili</p>
                <button class="start">Başlayın</button>
            </div>

            <div class="exams">
                <div class="img_div">
                    <img src="{% static 'images/science.svg' %}" alt="">
                    <div class="select-class">
                        <button><a href="">5-8</a></button>
                        <button><a href="">9-11</a></button>
                    </div>
                </div>
                <p>Informatika</p>
                <button class="start">Başlayın</button>
            </div>

            <div class="exams">
                <div class="img_div"> 
                    <img src="{% static 'images/open-book.png' %}" alt="">
                    <div class="select-class">
                        <button><a href="">5-8</a></button>
                        <button><a href="">9-11</a></button>
                    </div>
                </div>
                <p>Ingilis dili</p>
                <button class="start">Başlayın</button>
            </div>
            {% comment %} №№№№№№№№№№№№№№№№№№№№№№№№№ {% endcomment %}

            <div class="exams">
                <div class="img_div">
                    <img src="{% static 'images/math.svg' %}" alt="">
                    <div class="select-class">
                        <button><a href="">5-8</a></button>
                        <button><a href="">9-11</a></button>
                    </div>
                </div>
                <p>Tarix</p>
                <button class="start">Başlayın</button>
            </div>

            <div class="exams">
                <div class="img_div">
                    <img src="{% static 'images/science.svg' %}" alt="">
                    <div class="select-class">
                        <button><a href="">5-8</a></button>
                        <button><a href="">9-11</a></button>
                    </div>
                </div>
                <p>Fizika</p>
                <button class="start">Başlayın</button>
            </div>

            <div class="exams">
                <div class="img_div">
                    <img src="{% static 'images/open-book.png' %}" alt="">
                    <div class="select-class">
                        <button><a href="">5-8</a></button>
                        <button><a href="">9-11</a></button>
                    </div>
                </div>
                <p>Kimya</p>
                <button class="start">Başlayın</button>
            </div>

            <div class="exams">
                <div class="img_div"> 
                    <img src="{% static 'images/math.svg' %}" alt="">
                    <div class="select-class">
                        <button><a href="">5-8</a></button>
                        <button><a href="">9-11</a></button>
                    </div>
                </div>
                <p>Coğrafiya</p>
                <button class="start">Başlayın</button>
            </div>


        </div>
    </div>

    <script src="{% static 'js/select-class.js' %}"></script>
    

{% endblock body %}

    

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block body %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/home-repo.css' %}">


    <div class="container">

        {% if messages %}
          <ul class="messages">
              {% for message in messages %}
                  <li class="{{ message.tags }}">{{ message }}</li>
              {% endfor %}
          </ul>
        {% endif %}

        
      <section class="homepage-content">
        <div class="left-content">
          <div class="left-content-text">
            <h1> Private Lessons Online
              <!-- Private <br />
              Lessons <br />
              Online -->
            </h1>
            <p>Don't Miss Out While You Are Away From School</p>
            <div class="buttons">
              <button class="btn book-lesson">Book a Lesson</button>
              <button class="btn pick-package">Pick a Package</button>
            </div>
          </div>
        </div>
        <div class="right-content">
          <img src="{% static 'images/girl-img.webp' %}" alt="Girl Image" class="girl-image" />
        </div>
      </section>
      

      <section class="reviews-section">
        <div class="reviews-left">
          <h2>Reviews</h2>
          <p>
            I'm a paragraph. Click here to add your own text and edit me.
          </p>
        </div>
        
        <div class="reviews-hr"><hr></div>

        <div class="reviews-right">
          <div class="slider">
            <div class="slides">
              <div class="slide">
                “I'm a testimonial. Click to edit me and add text that says
                something nice about you and your services. Let your customers
                review you and tell their friends how great you are.”
                <br />
                <h6>Lisa, Dina's mom</h6>
              </div>
              <div class="slide">
                “I'm a testimonial. Click to edit me and add text that says
                something nice about you and your services.”
                <br />
                <h6>Dan, Sally's dad</h6>
              </div>
              <div class="slide">
                “I'm a testimonial. Click to edit me and add text that says
                something nice about you and your services. Let your customers
                review you and tell their friends how great you are.”
                <br />
                <h6>Jason,Karen's dad</h6>
              </div>
            </div>
          </div>
          <div class="slider-dots">
            <span class="dot" onclick="currentSlide(1)"></span>
            <span class="dot" onclick="currentSlide(2)"></span>
            <span class="dot" onclick="currentSlide(3)"></span>
          </div>
        </div>
      </section>
    </div>

   

      <script src="{% static 'js/home.js' %}"></script>
     
{% endblock body %}

templates/login.html
{% extends "base.html" %}
{% load static %}

{% block body %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">

{% comment %}     
    <div class="container">
        <div class="register_form">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
            
                <button class="reg_btn" type="submit">Qeydiyyatdan keç</button>
                <a href="{% url 'account:login' %}">Eger hesabiniz varsa daxil olun</a>
            </form>
        </div>
    </div> {% endcomment %}



    

<div class="section">
            <div class="contact_div">
                <div class="main_div">
                    <h3>Daxil Olun</h3>

                    <div class="form_div">
                        <form action="#" method="post">
                            {% csrf_token %}
                            <div class="form-name">

                                <input placeholder="Adınız..." type="text" id="name" name="username" >
                            </div>

                            <div class="form-name">

                                <input placeholder="Şifrəniz..." type="password" id="name" name="password" >
                            </div>

                        
                            
                            <button type="submit" class="comment-btn">Daxil ol</button>
                            <a href="{% url 'account:register' %}" class="login">Əgər hesabınız yoxdursa qeydiyyatdan keçin...</a>
                            
                        </form>
                    </div>
                </div>
                
            </div>

           

       </div>
  </div>
{% endblock %}



{% comment %} 
    <div class="name_input">
                        <i class="fa-regular fa-user"></i>
                        <input type="text" name="username" placeholder="Full Name">

                    </div> {% endcomment %}

templates/math_resault.html
{% extends "base.html" %}
{% load static %}
{% block body %}
<link rel="stylesheet" href="{% static 'css/math_result.css' %}">
    
  <div class="container">
    <h3>Neticeniz:</h3>
    <p>Doğru: {{ correct }}</p>
    <p>Yanlış: {{ incorrect }}</p>

  </div>

{% endblock body %}

templates/register.html
{% extends "base.html" %}
{% load static %}

{% block body %}
    <link rel="stylesheet" href="{% static 'css/register.css' %}">

{% comment %}     
    <div class="container">
        <div class="register_form">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
            
                <button class="reg_btn" type="submit">Qeydiyyatdan keç</button>
                <a href="{% url 'account:login' %}">Eger hesabiniz varsa daxil olun</a>
            </form>
        </div>
    </div> {% endcomment %}



    

<div class="section">
            <div class="contact_div">
                <div class="main_div">
                    <h3>Qeydiyyatdan Keçin</h3>

                    <div class="form_div">
                        <form action="#" method="post">
                            {% csrf_token %}
                            <div class="form-name">

                                <input placeholder="Adınız..." type="text" id="name" name="username" >
                            </div>

                            <div class="form-name">

                                <input placeholder="Şifrəniz..." type="password" id="name" name="password" >
                            </div>

                            <div class="form-name">

                                <input placeholder="Şifrənizi təsdiqləyin..." type="password" id="name" name="confirm" >
                            </div>
                        
                            
                            <button type="submit" class="comment-btn">Qeydiyyatdan keç</button>
                            <a href="{% url 'account:login' %}" class="login">Əgər hesabınız varsa daxil olun...</a>
                        </form>
                    </div>
                </div>
                
            </div>



       </div>
  </div>
{% endblock %}



{% comment %} 
    <div class="name_input">
                        <i class="fa-regular fa-user"></i>
                        <input type="text" name="username" placeholder="Full Name">

                    </div> {% endcomment %}

templates/video_lessons.html
{% extends "base.html" %}
{% load static %}

{% block body %}
<link rel="stylesheet" href="{% static 'css/video_lessons.css' %}">
<link rel="stylesheet" href="{% static 'css/video_lessons-repo.css' %}">

<div class="container">
    <h1>Video Dərslər</h1>
    <div class="video-grid">
        {% for video in videos %}
        <div class="video-card">
            <a href="{{ video.youtube_url }}" target="_blank" class="video-link">
                <div class="video-info">
                    <h2 class="video-title">{{ video.title }}</h2>
                    <p class="video-description">{{ video.description }}</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}